In [2]:
# Numpyのインポート
import numpy as np

In [3]:
# 3階のテンソルの作成
a = np.array([[[0, 1, 2], [3, 4, 5], [6, 7, 8]],
             [[9, 10, 11], [12, 13, 14], [15, 16, 17]],
             [[18, 19, 20], [21, 22, 23], [24, 25, 26]]])
print(a)

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]


In [7]:
# 4階のテンソルへの変換
b = a.reshape(3, 3, 1, 3)
print(b)

[[[[ 0  1  2]]

  [[ 3  4  5]]

  [[ 6  7  8]]]


 [[[ 9 10 11]]

  [[12 13 14]]

  [[15 16 17]]]


 [[[18 19 20]]

  [[21 22 23]]

  [[24 25 26]]]]


### transposeメソッド

In [9]:
# 軸の入れ替え
c = a.transpose(0, 2, 1)
print(c)

[[[ 0  3  6]
  [ 1  4  7]
  [ 2  5  8]]

 [[ 9 12 15]
  [10 13 16]
  [11 14 17]]

 [[18 21 24]
  [19 22 25]
  [20 23 26]]]
