In [1]:
# Numpyのインポート
import numpy as np

---
## 基本的な配列

In [5]:
# 配列の作成
a = np.array([0, 1, 2])
print(a)

[0 1 2]


In [7]:
# 二次元配列の作成
b = np.array([[0, 1, 2], [3, 4, 5]])
print(b)

[[0 1 2]
 [3 4 5]]


In [12]:
# 三次元配列の作成
c = np.array([[[0, 1, 2], [3, 4, 5], [6, 7, 8]], [[9, 10, 11], [12, 13, 14], [15, 16, 17]]])
print(c)

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]]


In [13]:
# 形状と要素数の取得
print(np.shape(a))
print(np.size(a))

print(np.shape(b))
print(np.size(b))

print(np.shape(c))
print(np.size(c))

(3,)
3
(2, 3)
6
(2, 3, 3)
18


In [15]:
# len関数:リストの要素数をカウント
print(len(c))
print(len(np.array(c)))

2
2


---
## 配列の生成

In [17]:
# 全て0の配列
print(np.zeros(20))

#全て1の配列
print(np.ones(20))

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [19]:
# 乱数な数値で構成される配列
print(np.random.rand(30))

[0.86978443 0.18052286 0.86344277 0.87642134 0.50215681 0.32366345
 0.62277211 0.26598853 0.89114722 0.00747132 0.55453874 0.96074293
 0.99730747 0.23085557 0.72205013 0.93170322 0.05550951 0.19699608
 0.8083415  0.66066165 0.04987147 0.64486085 0.00939033 0.02283494
 0.52608332 0.7858531  0.92838688 0.52241901 0.67852879 0.79047938]


In [37]:
# 上記の多次元配列
print(np.ones((3, 2, 5)))

[[[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]]


### araange関数

In [34]:
# arange関数: arange(a, b, c) "a"から"b"まで"c"刻みで配列を生成
print(np.arange(0, 1, 0.01))

[0.   0.01 0.02 0.03 0.04 0.05 0.06 0.07 0.08 0.09 0.1  0.11 0.12 0.13
 0.14 0.15 0.16 0.17 0.18 0.19 0.2  0.21 0.22 0.23 0.24 0.25 0.26 0.27
 0.28 0.29 0.3  0.31 0.32 0.33 0.34 0.35 0.36 0.37 0.38 0.39 0.4  0.41
 0.42 0.43 0.44 0.45 0.46 0.47 0.48 0.49 0.5  0.51 0.52 0.53 0.54 0.55
 0.56 0.57 0.58 0.59 0.6  0.61 0.62 0.63 0.64 0.65 0.66 0.67 0.68 0.69
 0.7  0.71 0.72 0.73 0.74 0.75 0.76 0.77 0.78 0.79 0.8  0.81 0.82 0.83
 0.84 0.85 0.86 0.87 0.88 0.89 0.9  0.91 0.92 0.93 0.94 0.95 0.96 0.97
 0.98 0.99]


In [36]:
# 刻み幅を指定しない場合は1刻みになる
print(np.arange(20))

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


### linspace関数

In [44]:
# linspace(開始する値, 終了する値, 要素数)
print(np.linspace(0, 20, 4))
print(np.linspace(0, 20, 21))

[ 0.          6.66666667 13.33333333 20.        ]
[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17.
 18. 19. 20.]


In [45]:
# 要素数は指定しなければ"50"
print(np.linspace(0, 49))

[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17.
 18. 19. 20. 21. 22. 23. 24. 25. 26. 27. 28. 29. 30. 31. 32. 33. 34. 35.
 36. 37. 38. 39. 40. 41. 42. 43. 44. 45. 46. 47. 48. 49.]


### rashape関数

In [50]:
a = np.arange(30)
b = a.reshape(5, 6)
print(b)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]]


In [51]:
# 記法の別例
c = np.reshape(b, (6, 5))
print(c)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]
 [25 26 27 28 29]]


In [53]:
# 3次元配列への変換
d = c.reshape(3, 2, 5)
print(d)

[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]]

 [[10 11 12 13 14]
  [15 16 17 18 19]]

 [[20 21 22 23 24]
  [25 26 27 28 29]]]


In [54]:
# 1次元配列への変換
e = d.reshape(-1)
print(e)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29]


In [57]:
# 次元の異なる配列の和
f = np.array([10, 9, 8, 7, 6])
print(d + f)

[[[10 10 10 10 10]
  [15 15 15 15 15]]

 [[20 20 20 20 20]
  [25 25 25 25 25]]

 [[30 30 30 30 30]
  [35 35 35 35 35]]]
