In [1]:
# Numpyのインポート
import numpy as np

## 基本的な配列

In [5]:
# 配列の作成
a = np.array([0, 1, 2])
print(a)

[0 1 2]


In [7]:
# 二次元配列の作成
b = np.array([[0, 1, 2], [3, 4, 5]])
print(b)

[[0 1 2]
 [3 4 5]]


In [12]:
# 三次元配列の作成
c = np.array([[[0, 1, 2], [3, 4, 5], [6, 7, 8]], [[9, 10, 11], [12, 13, 14], [15, 16, 17]]])
print(c)

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]]


In [13]:
# 形状と要素数の取得
print(np.shape(a))
print(np.size(a))

print(np.shape(b))
print(np.size(b))

print(np.shape(c))
print(np.size(c))

(3,)
3
(2, 3)
6
(2, 3, 3)
18


In [15]:
# len関数:リストの要素数をカウント
print(len(c))
print(len(np.array(c)))

2
2


## 配列の生成

In [ ]:
# 全て