In [2]:
# Numpyのインポート
import numpy as np

In [11]:
# 3階のテンソルの作成
A = np.array([[[0, 1, 2], [3, 4, 5], [6, 7, 8]],
             [[9, 10, 11], [12, 13, 14], [15, 16, 17]],
             [[18, 19, 20], [21, 22, 23], [24, 25, 26]]])
print(A)

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]


In [12]:
# 4階のテンソルへの変換
B = A.reshape(3, 3, 1, 3)
print(B)

[[[[ 0  1  2]]

  [[ 3  4  5]]

  [[ 6  7  8]]]


 [[[ 9 10 11]]

  [[12 13 14]]

  [[15 16 17]]]


 [[[18 19 20]]

  [[21 22 23]]

  [[24 25 26]]]]


### transposeメソッド

In [13]:
# 軸の入れ替え
C = A.transpose(0, 2, 1)
print(C)

[[[ 0  3  6]
  [ 1  4  7]
  [ 2  5  8]]

 [[ 9 12 15]
  [10 13 16]
  [11 14 17]]

 [[18 21 24]
  [19 22 25]
  [20 23 26]]]


## 行列の計算

In [15]:
# 行列とスカラーの積
a = 4.3
D = a * A
print(D)

[[[  0.    4.3   8.6]
  [ 12.9  17.2  21.5]
  [ 25.8  30.1  34.4]]

 [[ 38.7  43.   47.3]
  [ 51.6  55.9  60.2]
  [ 64.5  68.8  73.1]]

 [[ 77.4  81.7  86. ]
  [ 90.3  94.6  98.9]
  [103.2 107.5 111.8]]]


In [16]:
# 要素ごとの積
E = np.array([[0, 1, 2],
              [3, 4, 5],
              [6, 7, 8]])
F = np.array([[9, 10, 11],
              [12, 13, 14],
              [15, 16, 17]])
G = E * F
print(G)

[[  0  10  22]
 [ 36  52  70]
 [ 90 112 136]]


### 行列積

In [17]:
H = np.dot(E, F)
print(H)

[[ 42  45  48]
 [150 162 174]
 [258 279 300]]


### 行列の転置

In [19]:
J = np.array([[0, 1, 2],
              [3, 4, 5]])
print(J)
print(J.T)

[[0 1 2]
 [3 4 5]]
[[0 3]
 [1 4]
 [2 5]]
